/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.mycompany.ruedalibros2.DAOUsersImpl;
import com.mycompany.ruedalibros2.Ventana;
import interfaces.DAOUsers;
import java.text.DateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.JTextField;
import modelos.usuarios;

/**
 *
 * @author Usuario
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        CargarUsuario();
        InitStyles();
        
    }
    public void InitStyles(){
        txtBuscar.putClientProperty("JTextField.placeholderText", "Ingrese el nombre de usuario a buscar");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUsuario = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setText("Usuarios");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 120, 40));

        btnNuevo.setBackground(new java.awt.Color(102, 102, 255));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 30));

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 30));

        btnBorrar.setBackground(new java.awt.Color(102, 102, 255));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 110, 30));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 550, 40));

        TableUsuario.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido P.", "Apellido M.", "Cedula", "Fecha de Nacimiento", "Estado civil", "Domicilio", "Teléfono", "Sancion", "Sancion dinero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableUsuario.getTableHeader().setReorderingAllowed(false);
        TableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableUsuarioMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TableUsuario);
        if (TableUsuario.getColumnModel().getColumnCount() > 0) {
            TableUsuario.getColumnModel().getColumn(0).setMinWidth(20);
            TableUsuario.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 850, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void CargarUsuario(){
        try{
           DAOUsers dao = new DAOUsersImpl(); 
           DefaultTableModel model = (DefaultTableModel) TableUsuario.getModel(); 
                    
           dao.listar("").forEach((u) -> model.addRow(new Object[] {u.getId(),u.getNombre(), u.getApellido1(), u.getApellido2(), u.getCedula(), 
                u.getEdad(), u.getEstado_civil(), u.getDomicilio(), u.getTelefono(), u.getSancion(), u.getSancion_dinero()}));       
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    private void TableUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsuarioMousePressed
        
    }//GEN-LAST:event_TableUsuarioMousePressed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Ventana.ShowJPanel(new SubirUsuario());
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       DAOUsers dao = new DAOUsersImpl();  
       DefaultTableModel model = (DefaultTableModel) TableUsuario.getModel();
       if(TableUsuario.getSelectedRows().length<1){
        javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar uno o más usuarios a eliminar \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

       }else{
        for(int i:TableUsuario.getSelectedRows()){
            try{
            int userId = (int)TableUsuario.getValueAt(i, 0);  
             dao.eliminar((int)TableUsuario.getValueAt(i, 0));
            model.removeRow(i);
           }catch(Exception e){
                System.out.println(e.getMessage());
        }
       }
        
       }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if(TableUsuario.getSelectedRow() > -1){
           try{
            int userId = (int) TableUsuario.getValueAt(TableUsuario.getSelectedRow(), 0);
            DAOUsers dao = new DAOUsersImpl();
            Ventana.ShowJPanel(new SubirUsuario(dao.getusuariobById(userId)));
           }catch(Exception e){
               System.out.println(e.getMessage());
           }
           
       }else{
           javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar el ususario a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
       } 
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        try {
            DAOUsers dao = new DAOUsersImpl();
            DefaultTableModel model = (DefaultTableModel) TableUsuario.getModel();
            model.setRowCount(0);
            dao.listar(txtBuscar.getText()).forEach((u) -> model.addRow(new Object[] {u.getId(),u.getNombre(), u.getApellido1(), u.getApellido2(), u.getCedula(), u.getEdad(), u.getEstado_civil(), u.getDomicilio(), u.getTelefono(), u.getSancion(), u.getSancion_dinero()}));
        }catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableUsuario;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
